using System;
using Newtonsoft.Json.Linq;

namespace JSONFileFromCodeGeneratorApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("JSON file generated by C# code:");
            Console.ForegroundColor = ConsoleColor.Red; // Generated JSON will be highlighted in different color
            JObject colorsInJson = JObject.Parse(Colors.SampleColors());
            Console.WriteLine(colorsInJson);

            Console.ResetColor();
            Console.WriteLine("Press any key on your keyboard to close the screen...");
            Console.ReadKey();
        }
    }
}
